[versions]
# Kotlin
kotlin = "2.3.0"

# Build tools
agp = "8.13.2"

# Testing (opcional - solo si vas a hacer tests)
junit = "4.13.2"
androidx-junit = "1.3.0"
androidx-espresso = "3.7.0"

[libraries]
# Testing libraries (opcional)
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-junit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-espresso" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
